### ISSUE TITLE
What is the distribuetd framework when training the model named BLIP-2 ViT-G FlanT5xxl?

### ISSUE THREAD

**Issue by qiao1025566574** [salesforce/LAVIS#172] opened 2023-03-05 15:46 UTC
The "BLIP-2 ViT-G Flan-T5-XXL" has 12.1B parameters. Therefore, how do you load this model to cuda memory? Do you use some skills like model sharding or the framework like Deepspeed?

**Comment by dxli94** [comment] 2023-03-06 05:49
Duplicate of https://github.com/salesforce/LAVIS/issues/166.

**Closed** 2023-03-06 08:29 UTC
Labels: duplicate
