### ISSUE TITLE
Problem with downloading the coco caption dataset

### ISSUE THREAD

**Issue by Thedatababbler** [salesforce/LAVIS#86] opened 2023-01-18 18:37 UTC
When I was follwoing the data downloading guidence to run the download script for cococaption with the following command,
`cd lavis/datasets/download_scripts && python download_coco.py`
I received this error:
`ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization' (.../LAVIS/lavis/lib/python3.8/site-packages/torch/ao/quantization/__init__.py)
`
So I googled this problem and find out this could be caused by the unmatched torch version. Nevertheless, I figured out some trick to bypass the prior problem and run the same script again. This time, the error showing before didn't show up but I received this the following warning:
`UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
`
And this problem, again, could be caused by the unmatched version of torch version.
I checked my torch version is 10.0, and that's the required version for this repository. So I wondering what would be the problem caused such error. Thanks.

**Comment by dxli94** [comment] 2023-01-26 13:57
hi @Thedatababbler , thanks for raising the issue.

We've updated requirement.txt to relax the pytorch version. Could you try with the newer torch version and see whether the issue persists? Please provide information about your platform and torch & torchvision versions if the issue is not resolved.

Thanks.

**Comment by dxli94** [comment] 2023-02-03 10:04
Closed as can't reproduce. Feel free to reopen if needed.

**Closed by dxli94** 2023-02-03 10:04 UTC
